apiVersion: v1
kind: Service

metadata:
  name: node-app

  labels:
    app.kubernetes.io/name: node-app

spec:

  type: {{ .Values.service.type }}

  selector:
    app.kubernetes.io/name: node-app

  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP